import { INavContent } from '../../../model/nav';

export const ACCOUNT_NAV_CONFIG: Record<string, INavContent> = {
  tenant: {    
    description: 'Measuring your advertising ROI and track and report website traffic.',
    topNav: [
      {
        name: 'Dashboard',
        routerLink: '/app/tenant',
        exact: true,
        activeIcon: 'assets/svg/dashboard-active.svg',
        hoverIcon: 'assets/svg/dashboard-hover.svg',
        inactiveIcon: 'assets/svg/dashboard-inactive.svg',
        showAddressVerificationButton: true,
      },
      {
        name: 'Location',
        routerLink: '/app/tenant/location',
        activeIcon: 'assets/svg/location-active.svg',
        hoverIcon: 'assets/svg/location-hover.svg',
        inactiveIcon: 'assets/svg/location-inactive.svg',
      },
      {
        name: 'Incident',
        routerLink: '/app/tenant/incident',
        activeIcon: 'assets/svg/incident-active.svg',
        hoverIcon: 'assets/svg/incident-hover.svg',
        inactiveIcon: 'assets/svg/incident.svg',
      },
      {
        name: 'Tenant',
        routerLink: '/app/tenant/tenant',
        activeIcon: 'assets/svg/tenant-active.svg',
        hoverIcon: 'assets/svg/tenant-hover.svg',
        inactiveIcon: 'assets/svg/tenant-inactive.svg',
        description: 'Manage and track all tenant property.'
      },
      {
        name: 'Address Verification',
        routerLink: '/app/tenant/address-verification',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
      {
        name: 'Verification Requests',
        routerLink: '/app/tenant/address-verification-requests',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        title: 'Address Verification Requests',
        description: 'Review and manage incoming verification requests.',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
    ],
    bottomNav: [
      {
        name: 'Settings',
        routerLink: '/app/tenant/settings',
        activeIcon: 'assets/svg/Setting-active.svg',
        hoverIcon: 'assets/svg/Setting-hover.svg',
        inactiveIcon: 'assets/svg/Setting-inactive.svg',
        description: 'Manage your profile, notifications, and security preferences.',
      },
      {
        name: 'Logout',
        routerLink: '/logout',
        activeIcon: 'assets/svg/Logout.svg',
        hoverIcon: 'assets/svg/Logout-hover.svg',
        inactiveIcon: 'assets/svg/Logout-inactive.svg',
      }
    ],
    hasProfileDisplay: false,
  },
  user: {
    description: 'Measuring your advertising ROI and track and report website traffic.',
    topNav: [
      {
        name: 'Dashboard',
        routerLink: '/app/user',
        exact: true,
        activeIcon: 'assets/svg/dashboard-active.svg',
        hoverIcon: 'assets/svg/dashboard-hover.svg',
        inactiveIcon: 'assets/svg/dashboard-inactive.svg',
        showAddressVerificationButton: true,
      },
      {
        name: 'Location',
        routerLink: '/app/user/location',
        activeIcon: 'assets/svg/location-active.svg',
        hoverIcon: 'assets/svg/location-hover.svg',
        inactiveIcon: 'assets/svg/location-inactive.svg',
      },
      {
        name: 'Incident',
        routerLink: '/app/user/incident',
        activeIcon: 'assets/svg/incident-active.svg',
        hoverIcon: 'assets/svg/incident-hover.svg',
        inactiveIcon: 'assets/svg/incident.svg',
      },
      {
        name: 'Address Verification',
        routerLink: '/app/user/address-verification',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
      {
        name: 'Verification Requests',
        routerLink: '/app/user/address-verification-requests',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        title: 'Address Verification Requests',
        description: 'Review and manage incoming verification requests.',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      }
    ],
    bottomNav: [
      {
        name: 'Settings',
        routerLink: '/app/user/settings',
        activeIcon: 'assets/svg/Setting-active.svg',
        hoverIcon: 'assets/svg/Setting-hover.svg',
        inactiveIcon: 'assets/svg/Setting-inactive.svg',
        description: 'Manage your profile, notifications, and security preferences.',
      },
      {
        name: 'Logout',
        routerLink: '/logout',
        activeIcon: 'assets/svg/Logout.svg',
        hoverIcon: 'assets/svg/Logout-hover.svg',
        inactiveIcon: 'assets/svg/Logout-inactive.svg',
      }
    ],
    hasProfileDisplay: false,
  },
  'business-account': {
    description: 'Measuring your advertising ROI and track and report website traffic.',
    topNav: [
      {
        name: 'Dashboard',
        routerLink: '/app/business-account',
        exact: true,
        activeIcon: 'assets/svg/dashboard-active.svg',
        hoverIcon: 'assets/svg/dashboard-hover.svg',
        inactiveIcon: 'assets/svg/dashboard-inactive.svg',
        showAddressVerificationButton: true,
        description: 'Keep track of tenants and other address rating.'
      },
      {
        name: 'Location',
        routerLink: '/app/business-account/location',
        activeIcon: 'assets/svg/location-active.svg',
        hoverIcon: 'assets/svg/location-hover.svg',
        inactiveIcon: 'assets/svg/location-inactive.svg',
      },
      {
        name: 'Incident',
        routerLink: '/app/business-account/incident',
        activeIcon: 'assets/svg/incident-active.svg',
        hoverIcon: 'assets/svg/incident-hover.svg',
        inactiveIcon: 'assets/svg/incident.svg',
        description: 'You can now report incident any time and day'
      },
      {
        name: 'Employees List',
        routerLink: '/app/business-account/employees',
        activeIcon: 'assets/svg/employee-active.svg',
        hoverIcon: 'assets/svg/employee-hover.svg',
        inactiveIcon: 'assets/svg/employee.svg',
        title: 'Employment Status',
      },
      {
        name: 'Branch',
        routerLink: '/app/business-account/branch',
        activeIcon: 'assets/svg/address-verification-active.svg',
        hoverIcon: 'assets/svg/address-verification-hover.svg',
        inactiveIcon: 'assets/svg/address-verification-inactive.svg',
      },
      // {
      //   name: 'Manager/Owner',
      //   routerLink: '/app/tenant/tenant',
      //   activeIcon: 'assets/svg/employee.svg',
      //   inactiveIcon: 'assets/svg/employee.svg',
      // }
      
      {
        name: 'Address Verification',
        routerLink: '/app/business-account/address-verification',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
      {
        name: 'Verification Requests',
        routerLink: '/app/business-account/address-verification-requests',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        title: 'Address Verification Requests',
        description: 'Review and manage incoming verification requests.',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
      {
        name: 'Employee Verification',
        routerLink: '/app/business-account/employee-verification',
        activeIcon: 'assets/svg/employee.svg',
        hoverIcon: 'assets/svg/employee.svg',
        inactiveIcon: 'assets/svg/employee.svg',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/address-verification.svg',
      },
    ],
    bottomNav: [
      {
        name: 'Settings',
        routerLink: '/app/business-account/settings',
        activeIcon: 'assets/svg/Setting-active.svg',
        hoverIcon: 'assets/svg/Setting-hover.svg',
        inactiveIcon: 'assets/svg/Setting-inactive.svg',
        description: 'Manage your profile, notifications, and security preferences.',
      },
      {
        name: 'Logout',
        routerLink: '/logout',
        activeIcon: 'assets/svg/Logout.svg',
        hoverIcon: 'assets/svg/Logout-hover.svg',
        inactiveIcon: 'assets/svg/Logout-inactive.svg',
      }
    ],
    hasProfileDisplay: true
  },
  'public-service': {
    description: 'Measuring your advertising ROI and track and report website traffic.',
    topNav: [
      {
        name: 'Dashboard',
        routerLink: '/app/public-service',
        exact: true,
        activeIcon: 'assets/svg/dashboard-active.svg',
        hoverIcon: 'assets/svg/dashboard-hover.svg',
        inactiveIcon: 'assets/svg/dashboard-inactive.svg',
        showAddressVerificationButton: true,
      },
      {
        name: 'Location',
        routerLink: '/app/public-service/location',
        activeIcon: 'assets/svg/location-active.svg',
        hoverIcon: 'assets/svg/location-hover.svg',
        inactiveIcon: 'assets/svg/location-inactive.svg',
      },
      {
        name: 'Incident',
        routerLink: '/app/public-service/incident',
        activeIcon: 'assets/svg/incident-active.svg',
        hoverIcon: 'assets/svg/incident-hover.svg',
        inactiveIcon: 'assets/svg/incident.svg',
      },
      {
        name: 'Urban Planning',
        routerLink: '/app/public-service/urban-planning',
        activeIcon: 'assets/svg/urban-planning.svg',
        hoverIcon: 'assets/svg/urban-planning-hover.svg',
        inactiveIcon: 'assets/svg/urban-planning.svg',
      },
      {
        name: 'Social Amenities',
        routerLink: '/app/public-service/social-amenities',
        activeIcon: 'assets/svg/amenities.svg',
        hoverIcon: 'assets/svg/amenities.svg',
        inactiveIcon: 'assets/svg/amenities.svg',
      },
      {
        name: 'Business',
        routerLink: '/app/public-service/business',
        activeIcon: 'assets/svg/business.svg',
        hoverIcon: 'assets/svg/business-hover.svg',
        inactiveIcon: 'assets/svg/business.svg',
      },
      {
        name: 'Address Verification',
        routerLink: '/app/public-service/address-verification',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
      {
        name: 'Verification Requests',
        routerLink: '/app/public-service/address-verification-requests',
        activeIcon: 'assets/svg/verification-active.svg',
        hoverIcon: 'assets/svg/verification-hover.svg',
        inactiveIcon: 'assets/svg/verification-inactive.svg',
        title: 'Address Verification Requests',
        description: 'Review and manage incoming verification requests.',
        menuGroup: 'verification',
        menuGroupLabel: 'Verification',
        menuGroupIcon: 'assets/svg/verification-inactive.svg',
      },
    ],
    bottomNav: [
      {
        name: 'Settings',
        routerLink: '/app/public-service/settings',
        activeIcon: 'assets/svg/Setting-active.svg',
        hoverIcon: 'assets/svg/Setting-hover.svg',
        inactiveIcon: 'assets/svg/Setting-inactive.svg',
        description: 'Manage your profile, notifications, and security preferences.',
      },
      {
        name: 'Logout',
        routerLink: '/logout',
        activeIcon: 'assets/svg/Logout.svg',
        hoverIcon: 'assets/svg/Logout-hover.svg',
        inactiveIcon: 'assets/svg/Logout-inactive.svg',
      }
    ],
    hasProfileDisplay: false
  },
};

